CARDS = [
    # ── MAJOR ARCANA ──────────────────────────────────────────────────────────
    {"name": "The Fool", "vi": "Kẻ Ngốc"},
    {"name": "The Magician", "vi": "Nhà Ảo Thuật"},
    {"name": "The High Priestess", "vi": "Nữ Tư Tế"},
    {"name": "The Empress", "vi": "Nữ Hoàng"},
    {"name": "The Emperor", "vi": "Hoàng Đế"},
    {"name": "The Hierophant", "vi": "Giáo Chủ"},
    {"name": "The Lovers", "vi": "Tình Nhân"},
    {"name": "The Chariot", "vi": "Cỗ Xe"},
    {"name": "Strength", "vi": "Sức Mạnh"},
    {"name": "The Hermit", "vi": "Ẩn Sĩ"},
    {"name": "Wheel of Fortune", "vi": "Bánh Xe Vận Mệnh"},
    {"name": "Justice", "vi": "Công Lý"},
    {"name": "The Hanged Man", "vi": "Người Treo Ngược"},
    {"name": "Death", "vi": "Cái Chết"},
    {"name": "Temperance", "vi": "Điều Độ"},
    {"name": "The Devil", "vi": "Ác Quỷ"},
    {"name": "The Tower", "vi": "Tháp"},
    {"name": "The Star", "vi": "Ngôi Sao"},
    {"name": "The Moon", "vi": "Mặt Trăng"},
    {"name": "The Sun", "vi": "Mặt Trời"},
    {"name": "Judgement", "vi": "Phán Xét"},
    {"name": "The World", "vi": "Thế Giới"},

    # ── WANDS (GẬY) ───────────────────────────────────────────────────────────
    {"name": "Ace of Wands", "vi": "Át Gậy"},
    {"name": "Two of Wands", "vi": "2 Gậy"},
    {"name": "Three of Wands", "vi": "3 Gậy"},
    {"name": "Four of Wands", "vi": "4 Gậy"},
    {"name": "Five of Wands", "vi": "5 Gậy"},
    {"name": "Six of Wands", "vi": "6 Gậy"},
    {"name": "Seven of Wands", "vi": "7 Gậy"},
    {"name": "Eight of Wands", "vi": "8 Gậy"},
    {"name": "Nine of Wands", "vi": "9 Gậy"},
    {"name": "Ten of Wands", "vi": "10 Gậy"},
    {"name": "Page of Wands", "vi": "Tùy Tùng Gậy"},
    {"name": "Knight of Wands", "vi": "Kỵ Sĩ Gậy"},
    {"name": "Queen of Wands", "vi": "Nữ Hoàng Gậy"},
    {"name": "King of Wands", "vi": "Vua Gậy"},

    # ── CUPS (CỐC) ────────────────────────────────────────────────────────────
    {"name": "Ace of Cups", "vi": "Át Cốc"},
    {"name": "Two of Cups", "vi": "2 Cốc"},
    {"name": "Three of Cups", "vi": "3 Cốc"},
    {"name": "Four of Cups", "vi": "4 Cốc"},
    {"name": "Five of Cups", "vi": "5 Cốc"},
    {"name": "Six of Cups", "vi": "6 Cốc"},
    {"name": "Seven of Cups", "vi": "7 Cốc"},
    {"name": "Eight of Cups", "vi": "8 Cốc"},
    {"name": "Nine of Cups", "vi": "9 Cốc"},
    {"name": "Ten of Cups", "vi": "10 Cốc"},
    {"name": "Page of Cups", "vi": "Tùy Tùng Cốc"},
    {"name": "Knight of Cups", "vi": "Kỵ Sĩ Cốc"},
    {"name": "Queen of Cups", "vi": "Nữ Hoàng Cốc"},
    {"name": "King of Cups", "vi": "Vua Cốc"},

    # ── SWORDS (KIẾM) ─────────────────────────────────────────────────────────
    {"name": "Ace of Swords", "vi": "Át Kiếm"},
    {"name": "Two of Swords", "vi": "2 Kiếm"},
    {"name": "Three of Swords", "vi": "3 Kiếm"},
    {"name": "Four of Swords", "vi": "4 Kiếm"},
    {"name": "Five of Swords", "vi": "5 Kiếm"},
    {"name": "Six of Swords", "vi": "6 Kiếm"},
    {"name": "Seven of Swords", "vi": "7 Kiếm"},
    {"name": "Eight of Swords", "vi": "8 Kiếm"},
    {"name": "Nine of Swords", "vi": "9 Kiếm"},
    {"name": "Ten of Swords", "vi": "10 Kiếm"},
    {"name": "Page of Swords", "vi": "Tùy Tùng Kiếm"},
    {"name": "Knight of Swords", "vi": "Kỵ Sĩ Kiếm"},
    {"name": "Queen of Swords", "vi": "Nữ Hoàng Kiếm"},
    {"name": "King of Swords", "vi": "Vua Kiếm"},

    # ── PENTACLES (XU) ────────────────────────────────────────────────────────
    {"name": "Ace of Pentacles", "vi": "Át Xu"},
    {"name": "Two of Pentacles", "vi": "2 Xu"},
    {"name": "Three of Pentacles", "vi": "3 Xu"},
    {"name": "Four of Pentacles", "vi": "4 Xu"},
    {"name": "Five of Pentacles", "vi": "5 Xu"},
    {"name": "Six of Pentacles", "vi": "6 Xu"},
    {"name": "Seven of Pentacles", "vi": "7 Xu"},
    {"name": "Eight of Pentacles", "vi": "8 Xu"},
    {"name": "Nine of Pentacles", "vi": "9 Xu"},
    {"name": "Ten of Pentacles", "vi": "10 Xu"},
    {"name": "Page of Pentacles", "vi": "Tùy Tùng Xu"},
    {"name": "Knight of Pentacles", "vi": "Kỵ Sĩ Xu"},
    {"name": "Queen of Pentacles", "vi": "Nữ Hoàng Xu"},
    {"name": "King of Pentacles", "vi": "Vua Xu"},
]

# List for dropdown display: "Tên Việt (English Name)"
CARD_OPTIONS = [f"{c['vi']} ({c['name']})" for c in CARDS]
